### ISSUE TITLE
use the activity more streaming server 

### ISSUE THREAD

**Issue by Rawkush** [Rawkush/RawAnime#6]
only one link is fetched for the website and if that doesn't work can see times, however, using MoreStreaming server link will allow the alternatives

**Comment by balvinderz** [comment]
you can scrape rapidvideo website to get download link of the anime and then play it using android mediaplayer or exoplayer.

**Comment by Rawkush** [comment]
@balvinderz  thanks for the info, btw i just added the webview for viewing the animes inside the app which shows only video blocking all ads, will use your idea in future maybe

**Comment by Rawkush** [comment]
btw i have also shifted the scraping part in another repository named GogoScraper, in case you want to contribute .

I am closing this issue for now because in webview i have access to all servers, if  you want you can reopen the issue
